### ISSUE TITLE
Notes on project structure

### ISSUE THREAD

**Issue by khufkens** [padasch/ms_thermal_acclimation#1]
In the main README:

- `renv::snapshot()` should be `renv::restore()` to recreate the environment.
- note that all files analysis should be executed sequentially and can't be run independent

This is non critical but a note for the future:
All these statements are roughly the same for each paper / author combo:
https://github.com/padasch/ms_thermal_acclimation/blob/8a7d09449f50e2f6b3c11c54ad668e66597c69ea/analysis/01_wrangling_ACi-TGlob_V1.0.R#L360

Never write code twice, this could have been a loop / lapply / map reducing the code length by the number of lines per chunk x authors.

Avoid piping into `ggplot` this reads poorly and will decrease your code's performance if plotting on the same object multiple times. Again, don't write code twice.
https://github.com/padasch/ms_thermal_acclimation/blob/8a7d09449f50e2f6b3c11c54ad668e66597c69ea/analysis/03_model_sensitivity_analysis.R#L212

also

- add roxygen documentation for the functions, you will thank me later
- never use `paste()` to format paths, use `file.path()` so you are system agnostic, see:
https://github.com/padasch/ms_thermal_acclimation/blob/8a7d09449f50e2f6b3c11c54ad668e66597c69ea/R/functions/make_new_dynamic_dir.R#L37
- keep code under 130 characters with line breaks

**Comment by padasch** [comment]
Thank you for the review! I have fixed the README issues. Notes taken on your other comments too!
